// <auto-generated />
using DemoMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240924041428_Create_table_Person")]
    partial class Create_table_Person
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("DemoMVC.Models.Nguoi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Addrest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nguoi");
                });

            modelBuilder.Entity("DemoMVC.Models.Sinhvien", b =>
                {
                    b.Property<string>("Masv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Daichi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tensv")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Masv");

                    b.ToTable("Sinhvien");
                });
#pragma warning restore 612, 618
        }
    }
}
